"""Build notebooks/phishpedia_colab.ipynb for downloading the PhishPedia 30k benchmark in Colab."""

import json
from pathlib import Path

CELLS = [
    # 1. Title / overview
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "# PhishPedia Dataset Download + Layout Inspection\n",
            "\n",
            "Downloads the official **PhishPedia 30k benchmark** (~18 GB, CC0-1.0) into Colab's\n",
            "ephemeral disk, extracts it, and prints the layout facts the `phishme` V3 adapter\n",
            "needs (split CSV header, label vocabulary, HTML directory structure).\n",
            "\n",
            "- Source: official Google Drive link from `github.com/lindsey98/Phishpedia`\n",
            "  (`https://drive.google.com/file/d/12ypEMPRQ43zGRqHGut0Esq2z5en0DH4g/view`)\n",
            "- License: CC0-1.0\n",
            "- Disk budget: ~18 GB zip + ~20 GB extracted fits Colab free tier (~78 GB).\n",
            "- Runtime: download + extract typically 15-40 min on Colab's connection.\n",
            "\n",
            "**Run cells top to bottom. After cell 6, copy its layout output back to Hermes** so\n",
            "the `phishpedia.py` file-name mapping can be confirmed before training."
        ],
    },
    # 2. Setup: drive mount (optional) + deps + disk check
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# --- Setup ---\n",
            "# Optional: mount Drive ONLY if you want small artifacts (reports, models) persisted\n",
            "# across sessions. The 18 GB dataset itself stays on Colab's ephemeral disk.\n",
            "try:\n",
            "    from google.colab import drive\n",
            "    drive.mount(\"/content/drive\")\n",
            "    DRIVE_ARTIFACT_DIR = \"/content/drive/MyDrive/phishme-v3\"\n",
            "    print(\"Drive mounted; artifacts will be saved to\", DRIVE_ARTIFACT_DIR)\n",
            "except Exception as exc:  # non-Colab runtime or mount skipped\n",
            "    DRIVE_ARTIFACT_DIR = None\n",
            "    print(\"Drive not mounted (optional):\", exc)\n",
            "\n",
            "!pip install -q gdown\n",
            "\n",
            "import shutil\n",
            "import subprocess\n",
            "\n",
            "total, used, free = shutil.disk_usage(\"/content\")\n",
            "print(f\"Colab disk: {free / 1e9:.1f} GB free (need ~40 GB for zip + extract)\")\n",
            "assert free > 40e9, \"Not enough disk on this Colab session - use a fresh runtime\""
        ],
    },
    # 3. Keep-alive
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# Keep the Colab session connected while the long download runs.\n",
            "from IPython.display import display, Javascript\n",
            "\n",
            "display(\n",
            "    Javascript(\n",
            "        \"\"\"\n",
            "    function ClickConnect() {\n",
            "      const btn = document.querySelector('colab-connect-button');\n",
            "      if (btn) { btn.click(); }\n",
            "    }\n",
            "    setInterval(ClickConnect, 60000);\n",
            "    \"\"\"\n",
            "    )\n",
            ")\n",
            "print(\"Keep-alive armed.\")"
        ],
    },
    # 4. Download
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# --- Download (~18 GB) ---\n",
            "import os\n",
            "import time\n",
            "\n",
            "FILE_ID = \"12ypEMPRQ43zGRqHGut0Esq2z5en0DH4g\"\n",
            "URL = f\"https://drive.google.com/uc?id={FILE_ID}\"\n",
            "DEST = \"/content/phishpedia/phishpedia_dataset.zip\"\n",
            "os.makedirs(os.path.dirname(DEST), exist_ok=True)\n",
            "\n",
            "if os.path.exists(DEST) and os.path.getsize(DEST) > 10e9:\n",
            "    print(\"Download already present and >10 GB; skipping.\")\n",
            "else:\n",
            "    # gdown --fuzzy resolves the share-link confirm page for large public files.\n",
            "    # Retry loop: Google Drive occasionally answers 'quota exceeded' for hot files.\n",
            "    last = None\n",
            "    for attempt in range(1, 4):\n",
            "        print(f\"Attempt {attempt}/3: downloading {URL}\")\n",
            "        rc = subprocess.run(\n",
            "            [\"gdown\", \"--fuzzy\", URL, \"-O\", DEST],\n",
            "            capture_output=True,\n",
            "            text=True,\n",
            "        )\n",
            "        last = rc\n",
            "        if rc.returncode == 0 and os.path.exists(DEST) and os.path.getsize(DEST) > 10e9:\n",
            "            break\n",
            "        print(rc.stdout[-2000:])\n",
            "        print(rc.stderr[-2000:])\n",
            "        print(\"Quota/network issue; waiting 60 s before retry...\")\n",
            "        time.sleep(60)\n",
            "\n",
            "size = os.path.getsize(DEST) if os.path.exists(DEST) else 0\n",
            "print(f\"Downloaded: {size / 1e9:.2f} GB -> {DEST}\")\n",
            "assert size > 10e9, f\"Download looks wrong: {size} bytes (expected ~18 GB)\""
        ],
    },
    # 5. Extract with progress
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# --- Extract (~20 GB) ---\n",
            "import zipfile\n",
            "\n",
            "EXTRACT_DIR = \"/content/phishpedia/data\"\n",
            "os.makedirs(EXTRACT_DIR, exist_ok=True)\n",
            "\n",
            "if os.listdir(EXTRACT_DIR):\n",
            "    print(\"Extract dir not empty; skipping extraction.\")\n",
            "else:\n",
            "    with zipfile.ZipFile(DEST) as archive:\n",
            "        members = archive.infolist()\n",
            "        print(f\"Archive entries: {len(members)}\")\n",
            "        for index, member in enumerate(members, 1):\n",
            "            archive.extract(member, EXTRACT_DIR)\n",
            "            if index % 500 == 0 or index == len(members):\n",
            "                print(f\"  extracted {index}/{len(members)} entries\")\n",
            "\n",
            "total, used, free = shutil.disk_usage(\"/content\")\n",
            "print(f\"Extract done. Disk free now: {free / 1e9:.1f} GB\")"
        ],
    },
    # 6. Layout inspection
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# --- Layout inspection (the facts the phishme adapter needs) ---\n",
            "import glob\n",
            "from collections import Counter\n",
            "\n",
            "import pandas as pd\n",
            "\n",
            "root = Path(EXTRACT_DIR)\n",
            "\n",
            "# 6a. The split CSV\n",
            "csvs = sorted(glob.glob(str(root / \"**\" / \"*.csv\"), recursive=True))\n",
            "print(\"CSV files found:\")\n",
            "for path in csvs:\n",
            "    print(\"  \", path)\n",
            "\n",
            "CSV_PATH = None\n",
            "for path in csvs:\n",
            "    candidate = pd.read_csv(path, nrows=3)\n",
            "    if {\"url\", \"file_name\"}.issubset(candidate.columns):\n",
            "        CSV_PATH = path\n",
            "        break\n",
            "\n",
            "if CSV_PATH:\n",
            "    frame = pd.read_csv(CSV_PATH)\n",
            "    print(f\"\\nSplit CSV: {CSV_PATH}\")\n",
            "    print(f\"Rows: {len(frame)}\")\n",
            "    print(f\"Columns: {list(frame.columns)}\")\n",
            "    print(\"\\nFirst 5 rows:\")\n",
            "    print(frame.head().to_string())\n",
            "    for column in (\"label\", \"type\", \"split\"):\n",
            "        if column in frame.columns:\n",
            "            print(f\"\\n{column} value counts:\")\n",
            "            print(frame[column].value_counts(dropna=False).to_string())\n",
            "else:\n",
            "    print(\"\\nNo split CSV with url/file_name columns found - report this layout to Hermes.\")\n",
            "\n",
            "# 6b. HTML directories\n",
            "html_files = sorted(glob.glob(str(root / \"**\" / \"*.html\"), recursive=True))\n",
            "html_files += sorted(glob.glob(str(root / \"**\" / \"*.htm\"), recursive=True))\n",
            "print(f\"\\nTotal HTML files: {len(html_files)}\")\n",
            "top_level = Counter(Path(path).relative_to(root).parts[0] for path in html_files)\n",
            "print(\"HTML files per top-level directory:\")\n",
            "for directory, count in top_level.most_common():\n",
            "    print(f\"  {directory}: {count}\")\n",
            "print(\"\\n5 example HTML relative paths:\")\n",
            "for path in html_files[:5]:\n",
            "    print(\"  \", Path(path).relative_to(root))\n",
            "\n",
            "# 6c. Depth-2 tree of the extract root\n",
            "print(\"\\nDirectory tree (depth 2):\")\n",
            "for base, dirs, files in os.walk(root):\n",
            "    depth = len(Path(base).relative_to(root).parts)\n",
            "    if depth <= 2:\n",
            "        print(\"  \" * depth + os.path.basename(base) + \"/\")\n",
            "        if depth < 2:\n",
            "            for name in sorted(files)[:5]:\n",
            "                print(\"  \" * (depth + 1) + name)\n",
            "\n",
            "# 6d. Persist discovered paths for the optional training cell\n",
            "PHISH_HTML_DIR = None\n",
            "BENIGN_HTML_DIR = None\n",
            "print(\"\\nDiscovered paths saved to variables: CSV_PATH, PHISH_HTML_DIR, BENIGN_HTML_DIR\")\n",
            "print(\"(set in the optional v3-train cell if the structure is obvious, e.g. one dir per class)\")"
        ],
    },
    # 7. Next steps markdown
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## Next steps\n",
            "\n",
            "1. **Copy the cell-6 output** (CSV header, value counts, HTML directory counts, sample\n",
            "   paths, tree) back to Hermes. It verifies the `phishpedia.py` adapter's\n",
            "   `file_name -> HTML path` rule (expected: `root/<file_name>.html`) and records the\n",
            "   observed layout in `Implement.md` (plan Task 0).\n",
            "2. Then either run the **optional training cell** below in this same session, or\n",
            "   download the small run artifacts (`v3-run/` directory) to your machine and run\n",
            "   `v3-eval` there once the PhreshPhish test split and PhishLang predictions exist.\n",
            "\n",
            "The 18 GB dataset is **ephemeral**: it vanishes when the Colab session ends. Re-run\n",
            "cells 4-6 in a fresh session to re-download, or keep the session alive and run the\n",
            "training cell now."
        ],
    },
    # 8. Optional: clone phishme + v3-train (guarded)
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# --- OPTIONAL: train the V3 variants on PhishPedia in this session ---\n",
            "# Requires: (a) the phishMe repo's V3 code on GitHub (push main first), and\n",
            "#           (b) the layout inspection above to have identified the CSV + HTML roots.\n",
            "RUN_TRAIN = False  # set to True when Hermes confirms the adapter paths\n",
            "\n",
            "if RUN_TRAIN:\n",
            "    import subprocess\n",
            "    import sys\n",
            "\n",
            "    if not os.path.exists(\"/content/phishme\"):\n",
            "        subprocess.run([\"git\", \"clone\", \"https://github.com/Bookantna/phishMe.git\", \"/content/phishme\"], check=True)\n",
            "    %cd /content/phishme\n",
            "    subprocess.run([sys.executable, \"-m\", \"pip\", \"install\", \"-q\", \"-e\", \".[tree]\"], check=True)\n",
            "\n",
            "    help_run = subprocess.run(\n",
            "        [sys.executable, \"-m\", \"phishme\", \"v3-train\", \"--help\"],\n",
            "        capture_output=True,\n",
            "        text=True,\n",
            "    )\n",
            "    if help_run.returncode != 0:\n",
            "        print(\n",
            "            \"v3-train not found in the cloned repo - the remote main predates the V3 \"\n",
            "            \"rework. Push main to origin from the local machine, then re-run this cell.\"\n",
            "        )\n",
            "    else:\n",
            "        # Edit these three paths to match the layout printed by cell 6.\n",
            "        CSV = CSV_PATH\n",
            "        PHISH_HTML = PHISH_HTML_DIR or \"/content/phishpedia/data/<phishing-html-dir>\"\n",
            "        BENIGN_HTML = BENIGN_HTML_DIR or \"/content/phishpedia/data/<benign-html-dir>\"\n",
            "        print(subprocess.run(\n",
            "            [\n",
            "                sys.executable, \"-m\", \"phishme\", \"v3-train\",\n",
            "                \"--csv\", CSV, \"--phish-html\", PHISH_HTML, \"--benign-html\", BENIGN_HTML,\n",
            "                \"--output\", \"/content/phishpedia/v3-run\", \"--seed\", \"42\",\n",
            "            ],\n",
            "            capture_output=True,\n",
            "            text=True,\n",
            "        ).stdout[-4000:])\n",
            "        print(\"\\nArtifacts in /content/phishpedia/v3-run - download them to your machine.\")"
        ],
    },
]

NOTEBOOK = {
    "nbformat": 4,
    "nbformat_minor": 5,
    "metadata": {
        "colab": {"provenance": [], "name": "phishpedia_colab.ipynb"},
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3",
        },
        "language_info": {"name": "python"},
    },
    "cells": CELLS,
}

# Every cell needs a stable unique id (nbformat >= 5.1 requires them).
import uuid

for cell in NOTEBOOK["cells"]:
    cell.setdefault("id", uuid.uuid4().hex[:16])

path = Path(__file__).resolve().parent.parent / "notebooks" / "phishpedia_colab.ipynb"
path.write_text(json.dumps(NOTEBOOK, indent=1) + "\n", encoding="utf-8")
print(f"wrote {path} ({len(CELLS)} cells)")
